version: '3.6'
services:
  nsd:
    image: hardware/nsd-dnssec
    container_name: nsd
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./nsd/conf:/etc/nsd
      - ./nsd/zones:/zones
      - ./nsd/db:/var/db/nsd
